"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const index_js_1 = require("./index.js");
const parser = new index_js_1.GameParser({ hiraganas: 'きんにく' });
console.log(parser.input('k'));
console.log(parser.input('n'));
console.log(parser.input('i'));
console.log(parser.isComplete());
console.log(parser.inputedRoma);
console.log(parser.notInputedRoma);
